### ISSUE TITLE
wrong default compiler for i586-pc-windows-msvc

### ISSUE THREAD

**Issue by japaric** [alexcrichton/gcc-rs#108]
For `i586-pc-windows-msvc`, `gcc` uses `cl.exe` as the compiler but for `i686-pc-windows-msvc` uses the full path to the compiler: `C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\bin\\amd64_x86\\cl.exe`. The compilation fails in the former case with `"failed to execute command: The system cannot find the file specified. (os error 2)"`.

`gcc` should use the same compiler detection logic for both targets.

See these [AppVeyor][] [build] jobs.

[AppVeyor]: https://ci.appveyor.com/project/japaric/trust-mx72n/build/1.0.28/job/x5kc5m1rionsl08g#L120
[build]: https://ci.appveyor.com/project/japaric/trust-mx72n/build/1.0.29/job/r4ujhxhgt4hlpq4h#L99

**Comment by japaric** [comment]
Thanks for the fix, @alexcrichton! Could we get a new release with this fix?

**Comment by alexcrichton** [comment]
Sure!
