### ISSUE TITLE
Invoking clang

### ISSUE THREAD

**Issue by whitequark** [alexcrichton/gcc-rs#109]
My target does not have a gcc for it, only clang. (Nor a symlink from the `gcc` command.)

I would like to have a way to explicitly override the compiler binary used, or at least a name.

**Comment by alexcrichton** [comment]
The primary way to configure this crate is [environment variables](https://github.com/alexcrichton/gcc-rs#external-configuration-via-environment-variables) if you don't want to call [`Config::compiler`](http://alexcrichton.com/gcc-rs/gcc/struct.Config.html#method.compiler) yourself. Does that work for you?

**Comment by whitequark** [comment]
Ah, I somehow missed that I can do that. Looks like `CC=clang TARGET_CFLAGS="-target triple"` works.  Thanks!

By the way, aren't your `HOST`/`TARGET` definitions wrong? `HOST` should be `BUILD` and `TARGET` should be `HOST`.

**Comment by alexcrichton** [comment]
> HOST should be BUILD and TARGET should be HOST.

Perhaps, but Rust uses `--target`, not `--host`, for what's being compiled.

**Comment by whitequark** [comment]
Indeed, and that's correct, because rustc is a cross-compiler; so `--build` is where rustc is built, `--host` is where rustc is ran, and `--target` is where the output of rustc will run. See https://www.gnu.org/software/automake/manual/html_node/Cross_002dCompilation.html.
