### ISSUE TITLE
Rust <1.7 compatibility broken in #106 due to use of String::as_str

### ISSUE THREAD

**Issue by kamalmarhubi** [alexcrichton/gcc-rs#111]
Compatibility and semver [seem contentious](https://github.com/rust-lang/rfcs/pull/1619), but I just wanted to point this out. It's a tiny change to support 1.2 so I'll send the tiny PR to do so in a bit.

**Comment by kamalmarhubi** [comment]
Actually since `String::as_str` was stabilized in 1.7, this drops support for all earlier versions.

**Comment by alexcrichton** [comment]
Ah certainly unintentional! Feel free to send a PR!

**Comment by kamalmarhubi** [comment]
This was fixed in #110 which you just merged!

**Comment by fiveop** [comment]
Since this broke builds, I kindly ask for a new release.

**Comment by alexcrichton** [comment]
Published!
