### ISSUE TITLE
MSVC: warning: cl : Command line warning D9002 : ignoring unknown option '/SAFESEH'

### ISSUE THREAD

**Issue by Boscop** [alexcrichton/gcc-rs#112]
I'm building [this](https://github.com/rjanicek/liquidfun-rust/blob/master/src/build.rs) on `nightly-i686-pc-windows-msvc`, and I get this warning:
```
warning: cl : Command line warning D9002 : ignoring unknown option '/SAFESEH'
```
As far as I understand, `/SAFESEH` is a linker flag, the compiler cl.exe doesn't understand it. It should be passed to the linker instead.

**Comment by retep998** [comment]
This crate is indeed passing `/SAFESEH` to the compiler, which is incorrect.

https://github.com/alexcrichton/gcc-rs/blob/a97a973a8970d8f383043e34a88f177da36ecf78/src/lib.rs#L456-L461

**Comment by alexcrichton** [comment]
Fixed in https://github.com/alexcrichton/gcc-rs/commit/a514e25a85aede83b964ad922403243e664d80ce

**Comment by Boscop** [comment]
But shouldn't it be passed to the linker?

**Comment by alexcrichton** [comment]
It's been ignored up to now so presumably no, I forget the origins of why this was passed originally. I vaguely recall it being related to assembly, but not specifically C files.

**Comment by retep998** [comment]
The linker already passes `/SAFESEH` anyway. https://github.com/rust-lang/rust/blob/a5dac7a2af3ee444817eb7bfbba3539be8c06cf1/src/librustc_back/target/i686_pc_windows_msvc.rs#L25

Probably would be useful to pass `/EHs` to `cl.exe` though. It makes unwinding between C++ and Rust have sane behavior.

**Comment by Boscop** [comment]
Yeah, it would be useful to have proper unwinding from C++ exceptions!
