### ISSUE TITLE
Call emcc when building for emscripten

### ISSUE THREAD

**Issue by LaylConway** [alexcrichton/gcc-rs#113]
Supporting this could help port a number of different libraries that need to build individual C files to emscripten. A notable example is "flate2-rs", which needs to build "miniz.c", which can be compiled without errors by emcc.

**Comment by alexcrichton** [comment]
This [should happen by default](https://github.com/alexcrichton/gcc-rs/blob/master/src/lib.rs#L691-L699), but were you finding that it didn't?

**Comment by LaylConway** [comment]
Oh! My bad, I didn't know that was already a feature.
