### ISSUE TITLE
Add ATL/MFC include directories to MSVC compiler invocation if available

### ISSUE THREAD

**Issue by Jascha-N** [alexcrichton/gcc-rs#115]
The ATL/MFC include directory (`<VC directory>\atlmfc\include`) is currently not passed to `cl.exe`. The library directory (`<VC directory>\atlmfc\lib`, `<VC directory>\atlmfc\lib\arm` or `<VC directory>\atlmfc\lib\amd64`) are also not passed to the linker invocation. Mind you, the ATL and MFC libraries are not included with every installation of Visual Studio. 

If the idea is for the user to add these directories manually, it would be very useful if we could reuse the MSVC installation detection code in this crate. Maybe by adding a `find_vc_dir(target: &str)` function to `windows_registry`?

**Comment by alexcrichton** [comment]
Oh I'd be totally on board for adding support to this crate, they weren't intentionally left out or anything! If you've got a PR in mind to add support I'd be more than willing to merge!

**Comment by Jascha-N** [comment]
I've added the detection for ATL/MFC include and library detection in 5a05e13d5c32ceb011b929c5ff43b538421f3e12. The problem remains that the `rustc` compiler does not include the ATL/MFC lib directory when linking. Emitting a `cargo:rustc-link-search=native=...` from `gcc-rs` does not seem appropriate.

**Comment by alexcrichton** [comment]
Oh I think it'd be ok to emit that here for now, and then we can perhaps simultaneously submit a patch upstream as well to link that directory if it exists? (to match `cl.exe`)
