### ISSUE TITLE
support gcc executable being named something other than "cc"

### ISSUE THREAD

**Issue by dhduvall** [alexcrichton/gcc-rs#125]
If I'm reading the code correctly, the gcc crate assumes (on a unix-like environment, at least) that it can find gcc with the executable name `cc`.  This is not the case on Solaris, at least, and while I've been able to get around this by setting `$CC` (and by patching the source to force it to look for `gcc`, in some cases, or creating a special directory to add to `$PATH` and putting a symlink in there), it seems like it should just work out of the box. I really don't have a good idea what that should look like, though. Two thoughts that come to mind are

  - simply make it use `gcc` on all platforms, since that seems to be the default executable name, at least on Linux
  - new feature or other form of conditional compilation that sets the compiler executable path to something whoever's building the gcc crate can specify

**Comment by alexcrichton** [comment]
Oh this crate is intended to have reams of platform-specific code, so if you want to send a PR to change the default on Solaris I'd be totally fine with that! There's no guarantee that `cc` is used everywhere, currently. It's just the current catch-all.
