### ISSUE TITLE
Include compiled library

### ISSUE THREAD

**Issue by Kyroy** [alexcrichton/gcc-rs#129]
Is it possible to include an already compiled library?

I want to include https://github.com/scipr-lab/libsnark which has a bunch of dependencies and I don't know if I can get rust gcc to compile it with all the dependencies.

Libsnark (make) compiles a `libsnark.so` or `libsnark.a` depending on dynamic or static linking and I use `#[link(name = "snark")]`. I tried various ways of including the library but I always get: `= note: /usr/bin/ld: cannot find -lsnark`.

Thanks for your help in advance :)

**Comment by alexcrichton** [comment]
Hm I'm not sure I quite follow this issue, perhaps you could elaborate a bit more?

Compiled libraries are included via:

```rust
println!("cargo:rustc-link-lib=foo");
println!("cargo:rustc-link-search=path/to/find/foo");
```

But I'm not sure where the gcc crate comes into play?

**Comment by Kyroy** [comment]
I'm compiling the external library (here libsnark) before using `cargo build` and want it to be used from the gcc crate.
Normally you would use:
```-L/install/path/lib -lsnark -I/install/path/include```

I think it is possible to get the `-I` option with:
```
gcc::Config::new()
    .cpp(true)
    .include("/install/path/include")
    ...
```
and the `-lsnark` option with: `#[link(name = "snark")]`
but I am not sure how to link the actual library (here `libsnark.a` or `libsnark.so`) with the `-L` option.

I tried to work with `.flag("..")` and with the environment variable `CXXFLAGS` but I haven't figured it out, yet. Getting an error:
```
error: linking with `cc` failed: exit code: 1
...
  = note: /usr/bin/ld: cannot find -lsnark
          collect2: error: ld returned 1 exit status
```

**Comment by alexcrichton** [comment]
Oh if you're compiling the crate ahead of time then there's no need for the gcc crate, right? There's nothing left to compile when the build script runs? You can just print out the relevant annotations yourself?

**Comment by Kyroy** [comment]
Oh, yes :) Thank you for your help. Didn't know that this is possible :+1:

**Comment by Kyroy** [comment]
Well, actually there was something to compile, but I also needed pre-compiled libraries ;)
