### ISSUE TITLE
Add a version of expand returning a Result

### ISSUE THREAD

**Issue by sfackler** [alexcrichton/gcc-rs#133]
I have to do some dubious unwind catching for nice diagnostics unfortunately: https://github.com/sfackler/rust-openssl/pull/571

**Comment by alexcrichton** [comment]
Sounds good to me!

**Comment by dtolnay** [comment]
This is also tracked in #192.

**Comment by alexcrichton** [comment]
Fixed in https://github.com/alexcrichton/gcc-rs/pull/222
