### ISSUE TITLE
MSVC compilation errors are not shown

### ISSUE THREAD

**Issue by pornel** [alexcrichton/gcc-rs#141]
When `cl.exe` fails to compile a file, the gcc crate only displays `command did not execute successfully, got: exit code: 2`, but does not print errors generated by `cl.exe`.

Running the full `cl.exe` command manually does show errors, but copying&pasting commands in cmd prompt is incredibly tedious and error-prone, so it'd be very helpful if Cargo did not eat cl.exe's output.

> process didn't exit successfully: `C:\Users\user\proj\target\debug\build\libtest-sys-9e3214e9b9252129\build-script-build` (exit code: 101)
> --- stdout
> TARGET = Some("i686-pc-windows-msvc")
> OPT_LEVEL = Some("0")
> TARGET = Some("i686-pc-windows-msvc")
> HOST = Some("i686-pc-windows-msvc")
> TARGET = Some("i686-pc-windows-msvc")
> TARGET = Some("i686-pc-windows-msvc")
> HOST = Some("i686-pc-windows-msvc")
> CC_i686-pc-windows-msvc = None
> CC_i686_pc_windows_msvc = None
> HOST_CC = None
> CC = None
> TARGET = Some("i686-pc-windows-msvc")
> HOST = Some("i686-pc-windows-msvc")
> CFLAGS_i686-pc-windows-msvc = None
> CFLAGS_i686_pc_windows_msvc = None
> HOST_CFLAGS = None
> CFLAGS = None
> PROFILE = Some("debug")
> running: "C:\\Program Files\\Microsoft Visual Studio 14.0\\VC\\BIN\\cl.exe" "/nologo" "/MD" "/Z7" "/DUSE_SSE=1" "/FoC:\\Users\\user\\proj\\target\\debug\\build\\libtest-sys-96b972ed96e9414d\\out\\libtest.o" "/c" "libtest.c"
> ExitStatus(ExitStatus(2))> 
> 

> command did not execute successfully, got: exit code: 2> 
> 
> 

> --- stderr
> thread 'main' panicked at 'explicit panic', C:\Users\user\.cargo\registry\src\github.com-1ecc6299db9ec823\gcc-0.3.43\src\lib.rs:1127
> note: Run with `RUST_BACKTRACE=1` for a backtrace.

**Comment by alexcrichton** [comment]
Out of curiosity, did you think that this crate is intentionally trying to swallow up these errors? 

In any case, this is certainly not intentional. Is there any more debugging information you can offer to reproduce for example? I"ve never run into this locally at least when working with MSVC.

**Comment by pornel** [comment]
I don't want to imply intention, but I did assume Cargo and Command were capturing stderr to print it only under certain conditions, which probably didn't cover this one. Or maybe just Windows or msvc has stderr output done in a weird way.

To reproduce:

* Windows 10 VM from here: https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/
* Install VS studio tools recommended by rustup
* `rustup default nightly` (because stable Rust doesn't work at all on this vm)
* Cargo.toml: 

```toml
[package]
name = "foo"
version = "0.1.0"
authors = ["IEUser"]
build = "build.rs"

[build-dependencies]
gcc = "0"
```

* build.rs:

```rust
extern crate gcc;

fn main() {
     gcc::Config::new()
                .file("bork.c")
                .compile("libfoo.a");
}
```

* `echo bork > bork.c`
* `cargo build -v`

> running: "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\bin\\amd64\\cl.exe" "/nologo" "/MD" "/Z7" "/FoC:\\Users\\IEUser\\foo\\target\\debug\\build\\foo-d1afa518aed92cd9\\out\\bork.o" "/c" "bork.c"
ExitStatus(ExitStatus(2))
> command did not execute successfully, got: exit code: 2


But running the same from cmd.exe:

```sh
C:\Users\IEUser\foo> "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\bin\\amd64\\cl.exe" "/nologo" "/MD" "/Z7" "/FoC:\\Users\\IEUser\\foo\\target\\debug\\build\\foo-d1afa518aed92cd9\\out\\bork.o" "/c" "bork.c"
bork.c
bork.c(2): fatal error C1004: unexpected end-of-file found
```

**Comment by alexcrichton** [comment]
This crate doesn't capture the output of commands, and yes Cargo does. Cargo's been doing that for years with no issue, though.

**Comment by shepmaster** [comment]
I see something similar when running tests in AppVeyor:

```
     Running `C:\projects\cupid\target\debug\build\cupid-cdb2b23639ca70fa\build-script-build`
error: failed to run custom build command for `cupid v0.3.0 (file:///C:/projects/cupid)`
process didn't exit successfully: `C:\projects\cupid\target\debug\build\cupid-cdb2b23639ca70fa\build-script-build` (exit code: 101)
--- stdout
TARGET = Some("x86_64-pc-windows-msvc")
OPT_LEVEL = Some("0")
TARGET = Some("x86_64-pc-windows-msvc")
HOST = Some("x86_64-pc-windows-msvc")
TARGET = Some("x86_64-pc-windows-msvc")
TARGET = Some("x86_64-pc-windows-msvc")
HOST = Some("x86_64-pc-windows-msvc")
CC_x86_64-pc-windows-msvc = None
CC_x86_64_pc_windows_msvc = None
HOST_CC = None
CC = None
TARGET = Some("x86_64-pc-windows-msvc")
HOST = Some("x86_64-pc-windows-msvc")
CFLAGS_x86_64-pc-windows-msvc = None
CFLAGS_x86_64_pc_windows_msvc = None
HOST_CFLAGS = None
CFLAGS = None
PROFILE = Some("debug")
running: "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\bin\\amd64\\cl.exe" "/nologo" "/MD" "/Z7" "/DMSVC" "/FoC:\\projects\\cupid\\target\\debug\\build\\cupid-e0d03e0505cc1475\\out\\src/arch\\shim.o" "/c" "src/arch/shim.c"
ExitStatus(ExitStatus(2))
command did not execute successfully, got: exit code: 2
--- stderr
thread 'main' panicked at 'explicit panic', C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\gcc-0.3.44\src\lib.rs:1140
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

I'm going to try and get a local MSVC install to see if there's any useful output outside of AppVeyor.

**Comment by shepmaster** [comment]
Strangely, the code compiles with a local MSVC (which is going to make debugging AppVeyor tricky). If I add `#error "this is a bad thing"` to my code, I do see the [same behavior as before](https://github.com/alexcrichton/gcc-rs/issues/141#issuecomment-286911835), and no sign of the text "bad thing".

**Comment by shepmaster** [comment]
I think the problem comes from the fact that `stdout` is dropped on the floor. It's assigned [at line 1096](https://github.com/alexcrichton/gcc-rs/blob/36f19205be25c3a70fa8a1d93592a3e5ebbfa5f4/src/lib.rs#L1096), but we can fail the entire program at [line 1123](https://github.com/alexcrichton/gcc-rs/blob/36f19205be25c3a70fa8a1d93592a3e5ebbfa5f4/src/lib.rs#L1123), [line 1129](https://github.com/alexcrichton/gcc-rs/blob/36f19205be25c3a70fa8a1d93592a3e5ebbfa5f4/src/lib.rs#L1129) and [line 1133](https://github.com/alexcrichton/gcc-rs/blob/36f19205be25c3a70fa8a1d93592a3e5ebbfa5f4/src/lib.rs#L1133).

Thus, I think the problem isn't *specific* to MSVC, but rather that MSVC is outputting errors to standard output and that any information from stdout is ignored in these (and other?) failure cases.

**Comment by shepmaster** [comment]
Using a [quick hack to print out stdout in the 3 failure cases](https://github.com/shepmaster/gcc-rs/commit/715d461fdc4ba03614ff6fd1b0add80063b4ba0e) appears to be helping me in my case.

Any suggestions on how you'd like to see this kind of patch cleaned up for submission, @alexcrichton ?

**Comment by alexcrichton** [comment]
Ah that'd do it, thanks for the investigation @shepmaster!

This was introduced in https://github.com/alexcrichton/gcc-rs/commit/0084d5e0ee691720d7c7bb3aaee3cbfc15cd5796, so I think we should just refactor to have that one precise endpoint capture stdout and otherwise nothing else should. I'll go ahead and do that locally real quick.

**Comment by shepmaster** [comment]
Thank you!
