### ISSUE TITLE
musl: hardcoded `-static` causes issues with library objects

### ISSUE THREAD

**Issue by lucab** [alexcrichton/gcc-rs#165]
Capturing an issue first reported at https://github.com/briansmith/ring/issues/544

It looks like https://github.com/alexcrichton/gcc-rs/commit/f308ef2121a812c07718e15e689cbb1c90778513 introduced an hardcoded `-static` flag for musl-gcc invocation.
This seems to be introducing linking issues when building objects for native libraries, due to non-relocatable symbols.

**Comment by alexcrichton** [comment]
Would be good to fix! It seems like an application of something like `-fpic` would help here? I'm not really privvy to a number of the details here.

**Comment by lucab** [comment]
`-fPIC` would help, but as shown in the initial ticket it is not enough. `ring` already passes it as part of its custom build.rs logic, but the the static flag is still causing some symbols to be not relocatables.
The solution I submitted in there is to add a later custom `-shared` flag which override the earlier `-static` introduced by gcc-rs, but @isonmad was wondering if this can be avoided here.

**Comment by alexcrichton** [comment]
Sure yeah seems fine to have a flag to disable this behavior
