### ISSUE TITLE
Debug info on non-debug profiles

### ISSUE THREAD

**Issue by oyvindln** [alexcrichton/gcc-rs#171]
Currently the debug flag is set when compiling when PROFILE is set to debug. This does mean that debug symbols are not generated for the C/C++ code when not using the debug profile (unless it's manually set by the library). Wouldn't it make more sense to set it based on the DEBUG env variable, so debug symbols are generated based on whether the rust code gets compiled with debug symbols? One use for this is profiling, but there may be other cases where this could be useful too.

**Comment by alexcrichton** [comment]
Does [`Config::debug`](https://github.com/alexcrichton/gcc-rs/blob/48585c7a929313720854d5d28b235f06738762d4/src/lib.rs#L344-L353) work for your use case?

**Comment by oyvindln** [comment]
In my case I was using another crate that used gcc, rather than using it directly, so that wouldn't work. (Granted I realize this may be a bit of an edge case.)

**Comment by alexcrichton** [comment]
Ah ok, in that case I'm going to close this as this is implemented in this library and I think other consumers would then just want to expose configured if need be.
