### ISSUE TITLE
RFE: flag_if_supported

### ISSUE THREAD

**Issue by ronnychevalier** [alexcrichton/gcc-rs#173]
In [Tectonic](https://github.com/tectonic-typesetting/tectonic/), we have a lot of legacy C code for the moment (the end goal being having as less C code as possible). In the mean time, we want to improve the C code quality by using warning flags while not triggering errors on compilers not supporting such flags.

We [added](https://github.com/tectonic-typesetting/tectonic/commit/574621cdae6adaaa544c6c70f9ce28c60d829311) a wrapper around `gcc-rs`, called `flag_if_supported` to check whether a flag exists or not and add it to the list of flags if this is the case. Similar to [CHECK_C_COMPILER_FLAG](https://cmake.org/cmake/help/v3.0/module/CheckCCompilerFlag.html) from cmake.

The problem is that since we do not have access to the fields of `Config`, we have to duplicate some work to find the target, add the output file to the command, and add a duplicate of the `cpp` flag.

Would you be interested in having this feature directly in `gcc-rs`?

This way we would have direct access to the cpp flag, the target and add transparently the output file (for each target supported by `gcc-rs`). In addition, this would avoid implementing it in each `build.rs` needing this feature.

Related: #48 have a proposal about `try_compile`

**Comment by alexcrichton** [comment]
Sounds good to me!
