### ISSUE TITLE
Add panic conditions to various functions

### ISSUE THREAD

**Issue by brson** [alexcrichton/gcc-rs#181]
Per [guidelines](https://github.com/brson/rust-api-guidelines#c-panic-doc).

Here are some places where this lib panics:

- `Config::compile` can panic if `output` is not formatted correctly
- `Config::compile` calls `unwrap` on some files
- `Config::compile` can also panic if one of the underlying compiler commands fail

But do take another look and see if there are other asserts, unwraps and expects.

**Comment by rap2hpoutre** [comment]
I tried something [here](https://github.com/alexcrichton/gcc-rs/pull/211).

**Comment by opilar** [comment]
Is there something we missed or we can close this?

**Comment by alexcrichton** [comment]
I think we're good, yay!
