### ISSUE TITLE
Add warning control

### ISSUE THREAD

**Issue by brson** [alexcrichton/gcc-rs#190]
Do a few things:

- Turn on maximum warnings by default, in the compiler-specific way
- Add a method `warnings_as_errors` that turns warnings into errors in a compiler specific way

We haven't discussed this, but if we enable maximum warnings by default, it seems like some users will _not_ want that and a way to turn it off. So it seems like we should also add a `default_warnings` method that declines to set the maximum warnings.

**Comment by opilar** [comment]
How to create a static array and return a slice of it?
```rust
   --> src/lib.rs:164:34
    |
164 |             ToolFamily::Msvc => &["/Wall"],
    |                                  ^^^^^^^^-
    |                                  |       |
    |                                  |       temporary value only lives until here
    |                                  does not live long enough
    |
    = note: borrowed value must be valid for the static lifetime...
```

Method:
```rust
    /// What the flags to enable all warnings
    fn warnings_flags(&self) -> &'static [&'static str] {
        match *self {
            ToolFamily::Msvc => &["/Wall"],
            ToolFamily::Gnu => &["-Wall", "-Wpedantic", "-Wextra"],
            ToolFamily::Clang => &["-Weverything"],
        }
    }
```

**Comment by alexcrichton** [comment]
Hm I thought it was like that but I guess not :(. Maybe try making this not a method but instead a temporary in a function?

**Comment by dtolnay** [comment]
I agree with @pornel. Warnings enabled seems like the wrong default for the way this crate is usually used, and I would never want to use warnings-as-errors.
