### ISSUE TITLE
Add try_compile and try_expand

### ISSUE THREAD

**Issue by brson** [alexcrichton/gcc-rs#192]
As a build script the default mode is to just panic on error, but sometimes that is not appropriate. Add `try_compile` and `try_expand` methods that return a Result with a new enum type for the possible errors cases.

It probably makes sense to have the new error type`s `description` method return the current panic messages, and change the existing `try_compile`, `try_expand` methods to simply `panic!("{}", e.description())`.

This may require some internal refactoring to convert internal panics into Results.

**Comment by marco9999** [comment]
Hi, is this appropriate for someone new to rust to work on? I've finished reading through the second book, and would like to further improve my skills.

**Comment by alexcrichton** [comment]
@marco9999 sure! This'd mostly involve adding a custom error type, changing all panics to returning an error, and then propagating that result outwards to the API boundaries. We'd then rejigger the top-level APIs to have `compile` and `expand` panic while the `try_*` variants would return an error.

If you've got any questions just let me know!

**Comment by marco9999** [comment]
Great, I'll give it a go. Thanks!

**Comment by pornel** [comment]
Does the `try_compile` set any cargo flags?

I'm interested in testing whether certain compiler features or flags are supported, such as OpenMP (`-fopenmp`) or Intel-compiler-specific optimization settings. In old school configure scripts that's done by using a minimal file like `int main(void){}` and checking whether it compiles with the flags.

I would try to do the same with `gcc-rs`, but if `try_compile` implicitly prints instructions for Cargo, then I'm afraid I'd end up linking the actual Rust product with garbage from test files.

**Comment by alexcrichton** [comment]
@pornel I think a recent addition of `flag_if_supported` would suffice for that?

**Comment by pornel** [comment]
Yes, it's perfect!

**Comment by alexcrichton** [comment]
Fixed in https://github.com/alexcrichton/gcc-rs/pull/222
