### ISSUE TITLE
Explain what metadata is emitted by `cargo_metadata`

### ISSUE THREAD

**Issue by brson** [alexcrichton/gcc-rs#194]
This method is pretty vague about what it is doing. Make it more enlightening by explaining in the docs what it emits.

**Comment by laumann** [comment]
If I was going to take a stab at this, it seems that whenever `self.print()` is called, metadata is emitted if `cargo_metadata` is true.

From `Build::try_compile()`:
 - `self.print(&format!("cargo:rustc-link-search=native={}", atlmfc_lib.display()));`
 - `self.print(&format!("cargo:rustc-link-lib=static={}", &output[3..output.len() - 2]));`
 - `self.print(&format!("cargo:rustc-link-search=native={}", dst.display()));`
 - If self.cpp: `self.print(&format!("cargo:rustc-link-lib={}", stdlib));`

Environment variables also seem to be `self.print()`ed by `Build::getenv()`:
```
self.print(&format!("{} = {:?}", v, r));
```

The only place that really confuses me is `Build::ios_flags()` that makes the following call:
```
self.print(&format!("Detecting iOS SDK path for {}", sdk));
```

Just looking at the source, I would guess that the emitted cargo metadata is:
- `cargo:rustc-link-search`
- `cargo:rustc-link-lib`
- if the target is `msvc` then the ATL-MFC libs are added as well (via `cargo:rustc-link-search`)
- if C++ is enabled, then C++ stdlib is added as well (via `cargo:rustc-link-lib`)

Am I completely off?

**Comment by alexcrichton** [comment]
Yeah that all sounds right @laumann, thanks for looking into this!

Right now the `self.print` function is sort of just "debugging goo" in terms of some of it's cargo metadata (e.g. `cargo:key=value`) while other parts are just normal information. The "normal info" is intended to be used whenever a build script fails, so all that info is dumped to stdout for debugging.
