### ISSUE TITLE
Debug info should depend on the DEBUG var, not PROFILE

### ISSUE THREAD

**Issue by jonas-schievink** [alexcrichton/gcc-rs#220]
Currently, `gcc` [checks](https://github.com/alexcrichton/gcc-rs/blob/501a5bfb4add0f4f04bb6829bf3b8848fa08b207/src/lib.rs#L1230) if `PROFILE` is "debug" and enables debug info if so. I'm not sure if this was added recently, but Cargo [appears](http://doc.crates.io/environment-variables.html) to set the `DEBUG` env var to the `debug` setting in the active profile, which seems like a better variable to check.

If this is done, the compiled C code has debug info iff the Rust code has debug info (this isn't currently the case).

**Comment by alexcrichton** [comment]
Agreed! I think at the time of inception the DEBUG env var didn't exist...
