### ISSUE TITLE
Accept Into<Option<&str>> rather than Option<&str> in Config methods

### ISSUE THREAD

**Issue by dtolnay** [alexcrichton/gcc-rs#224]
There are currently three Config methods that take Option\<&str\>. It seems like they are commonly going to be called with Some string.

```rust
define("FOO", Some("BAR"))
```

Into\<Option\<&str\>\> could make the calls look neater.

```rust
define("FOO", "BAR")
define("FOO", None) // uncommon
```

**Comment by alexcrichton** [comment]
👍
