### ISSUE TITLE
Compiler flags disabling warnings have stopped working

### ISSUE THREAD

**Issue by pornel** [alexcrichton/gcc-rs#235]
In the latest version compilation of my crate outputs 280 [new unwanted warnings](https://github.com/alexcrichton/gcc-rs/issues/190#issuecomment-317925265).

The flags that I used to disable warnings have stopped working, so I can't tame that noise:

```rust
gcc::Config::new()
                .flag("-Wno-comment")
                .flag("-Wno-unused-parameter")
```

Please note that I'm compiling 3rd party code that I don't want to fork, so I'm unable to do anything about this flood of warnings.

**Comment by alexcrichton** [comment]
Does [turning warnings off](https://docs.rs/gcc/0.3.52/gcc/struct.Build.html#method.warnings) work for you?

**Comment by pornel** [comment]
Yes, it works. 

Could you make it off by default? 

This is a breaking change. For users who've had `-Werror` with only certain warnings enabled this will stop compilation. A sudden flood of irrelevant and unfixable warnings is not good either.

**Comment by alexcrichton** [comment]
Did your build break because of `-Werror`? Were any "unfixable" warnings not fixed by turning warnings off?

**Comment by pornel** [comment]
All warnings were disabled by `.warnings(false)`. That option in itself works and is sufficient.

However, this option and this behavior did not exist in previous semver-compatible version. This means that projects that used to build cleanly won't build cleanly after `cargo update`.

Personally I don't use `-Werror`, but someone else might have, and Cargo would break their build now.

I've meant warnings I get are unfixable, because in practice it's too difficult to prevent warnings by improving quality of the C code to compile without warnings (as opposed to telling compiler not to warn about bad code). I can't change C code, because I'm using `gcc-rs` to compile other people's code for `*-sys`-like crates, where the code is taken as-is from 3rd party repositories or system headers.

**Comment by alexcrichton** [comment]
Ok, just wanted to clarify if there was breakage.

I don't personally see a reason to have these off-by-default as that sort of defeats the purpose of the warnings. Most of the time this crate is intended for C/C++ shims that authors write rather than importing other projecs (which typically have their own build system), so I think the warnings being on is the right default. Projects can of course always choose to turn warnings off easily.
