### ISSUE TITLE
flag_if_supported does not work for C++ flags

### ISSUE THREAD

**Issue by jan-auer** [alexcrichton/gcc-rs#236]
`flag_if_supported()` does not work for flags that are C++ only. From what I can tell, this is because the file used to test the flag is a C file, which causes the compiler to throw up.

I use this to set the C++ standard, which would essentially solve #191 (unless you want to support this explicitly).

**Example configuration**

```rust
    gcc::Build::new()
        .cpp(true)
        .flag_if_supported("-std=c++14")
        .file("main.cpp")
        .compile("libtest.a");
```

**Comment by jan-auer** [comment]
Probably the easiest fix is to name the file `"flag_check.cpp"`, if cpp has been activated. That, however, would require the user to always call `cpp` before `flag_if_supported`. What do you think?

**Comment by alexcrichton** [comment]
I think it'd be fine if we deferred "check supported flags" until you actually hit the `compile` button. That way you could intermingle supported flags/cpp settings/etc. But yeah changing the name of the file seems fine by me!
