### ISSUE TITLE
Minimum rustc version bumped in patch version

### ISSUE THREAD

**Issue by danburkert** [alexcrichton/gcc-rs#240]
Hi, the minimum supported `rustc` version was [bumped in a patch version](https://github.com/alexcrichton/gcc-rs/commit/3cd8c8c44a2874c8500cf62065fe1734b5faf421). This is disruptive to downstream crates which have their own minimum supported `rustc` version, and which depend on `gcc` using a Cargo.toml directive like `gcc = "0.3"`.  Unless I'm misinterpreting the Cargo SemVer rules, it would be ideal if you could yank the affected versions.

**Comment by alexcrichton** [comment]
The rules around semver and "minimum supported rustc" are squishy at best, but the policy I personally use is at least 2 versions back from the current stable and otherwise updates can happen whenever. Are you unable to update rustc for other reasons though?

**Comment by danburkert** [comment]
No, I'm the author of a library which depends on `gcc`.  I personally consider it a breaking change to bump the minimum supported `rustc` version, since bumping the minimum version can be just as painful (or more) for downstream applications as breaking an API.

Now, speaking as the author of a (different) crate going through the lib blitz, it would be nice if this were standardized, since minimum rustc versions are viral.  I'm going to file an issue with the api-guidelines repository accordingly.

**Comment by alexcrichton** [comment]
Ok, in the case that it's not actively causing problems I'm going to go ahead and close this. This issue has come up many many times historically and we've never come up with a good guideline that's practical, but it's worth having a tracking issue!

**Comment by stevenroose** [comment]
We also just noticed this. What was the rationale for suddenly bumping MSRC from 1.16.0 to 1.31.0?? We're using `cc` in several libraries that support Rust 1.24.0 or sometimes 1.19.0 (respectively the latest on Debian Stretch and the latest mrustc supports), so support is suddenly broken.

What's worst is that it seems like the bump was just made for using the `crate::` use prefix..
```
$ rustup run 1.22.0 cargo build              
   Compiling cc v1.0.42
error: expected identifier, found keyword `crate`
  --> /home/steven/.cargo/registry/src/github.com-1ecc6299db9ec823/cc-1.0.42/src/windows_registry.rs:16:5
   |
16 | use crate::Tool;
   |     ^^^^^

error: aborting due to previous error

error: Could not compile `cc`.

To learn more, run the command again with --verbose
```

**Comment by alexcrichton** [comment]
There's an excellent comment explaining MSRV and maintainers [here](https://github.com/serde-rs/serde/issues/1602#issuecomment-522274093), I'd recommend reading over that personally.

I've decided to use the 2018 edition in this crate, so the minimum version is now 1.31.0.
