### ISSUE TITLE
link error

### ISSUE THREAD

**Issue by FillZpp** [alexcrichton/gcc-rs#26]
My project runs on Windows, there is an error `undefined reference to EnumProcesses` in c code.

I know the function `EnumProcesses()` defined in `libpsapi.a`, and i find this library in `C:\Rust\bin\rustlib\x86_64-pc-windows-gnu\lib`.

I tried to use `object()` and `flag()` in gcc-rs to link the library, but failed.

How can i fix it?

**Comment by alexcrichton** [comment]
This sounds like your build script should contain the line:

```rust
println!("cargo:rustc-flags -l psapi");
```

Does that fix it for you?

**Comment by FillZpp** [comment]
I add this line into `build.rs`. When runs `cargo.exe build --verbose`, it prints `Wrong output in build script of ...... : cargo:rusts-flags -l psapi`.

What's wrong?

**Comment by alexcrichton** [comment]
Ah sorry, `cargo:rustc-flags=-l psapi` is what it should print

**Comment by FillZpp** [comment]
Oh yes, think you very much!
