### ISSUE TITLE
PATH environment variable also required for Mac when gcc installed

### ISSUE THREAD

**Issue by ltfschoen** [alexcrichton/gcc-rs#27]
I tried using gcc-rs as follows:

**Cargo.toml** was updated with the following:
```
[package]
links = "hello"
build = "build.rs"

[build-dependencies.gcc]
git = "https://github.com/alexcrichton/gcc-rs"
```

**build.rs** file was created in the same directory as Cargo.toml with the following contents:

```
extern crate gcc;

fn main() {
    gcc::Config::new()
                .file("src/c/hello.c")
                .include("src")
                .compile("libhello.a");
}
```

**hello.c** source code was created in ./src/c/
```
#include <stdio.h>

void hello() {
    printf("Hello, World!\n");
}
```

**main.rs** Crate Root was created in ./src
```
use std::old_io;

fn main() {
    #[link(name="hello", kind="static")]
    extern { fn hello(); }
    unsafe { hello(); };
}
```

With this configuration, when I run ```cargo run``` it successfully compiles and prints "Hello, World!" in the terminal.

However, when I changed **Cargo.toml** to the following (instead of grabbing the gcc-rs dependency from the GitHub repo) I got the following errors, which indicates to me that something needs to be added to .bash_profile (the PATH) on Mac's too (I am using OSX 10.9.5). Currently the gcc-rs README file indicates that PATH updates only need to be made on Windows:
[build-dependencies]
gcc = "0.2"
```
build.rs:10:26: 10:31 error: mismatched types:
 expected `std::old_path::posix::Path`,
    found `&'static str`
(expected struct `std::old_path::posix::Path`,
    found &-ptr) [E0308]
build.rs:10                 .include("src")
```

I assume that .bashrc would need to be updated somehow?

```
if [ -d /Users/<username>/code/my_project ];
then
   GCC_LIBRARY_PATH=/Users/<username>/code/my_project:$LD_LIBRARY_PATH
fi

export GCC_LIBRARY_PATH
```

**Comment by alexcrichton** [comment]
It looks like in this case you'll just need to depend on 0.3 instead of 0.2 (to take care of the API differences). Feel free to reopen is there are still issues though!
