### ISSUE TITLE
Build on only stable rust

### ISSUE THREAD

**Issue by reem** [alexcrichton/gcc-rs#30]
Needed unstable APIs:

- [x] `std::convert::AsRef`

cc iron/iron#317

------------------------------

I'm filing this issue because this crate is part of iron or hyper's dependency chain, and I'm working with @aturon to get both building with only stable APIs for 1.0, so we are tracking used unstable APIs.

**Comment by SSheldon** [comment]
It's doable (see #33) but the API would be nicer if `convert` were stabilized.
