### ISSUE TITLE
Steer Windows users towards correct information about installing gcc

### ISSUE THREAD

**Issue by vadimcn** [alexcrichton/gcc-rs#35]
Given the confusing naming of various mingw forks floating around Internet, it is unlikely that inexperienced Windows users will manage to install the right one ([example](http://www.reddit.com/r/rust/comments/33r0xu/good_windows_setup_howto)).
I think we should supplement [is 'gcc' not installed?](https://github.com/alexcrichton/gcc-rs/blob/master/src/lib.rs#L255) message with a link to the corrent information.   Not sure where exactly...  we used to have "Windows" page in Rust wiki, but that is now gone.

**Comment by alexcrichton** [comment]
I'd be totally down with this! I wonder if perhaps we still have some docs lying around for windows installations though?
