### ISSUE TITLE
Output from gcc should be shown when the build fails

### ISSUE THREAD

**Issue by huonw** [alexcrichton/gcc-rs#36]
Currently a failing build (i.e. gcc returning an exit status != 0) just prints `command did not execute successfully, got: exit code: ...`, without providing any more detail about what the problem is. Printing stdout/stderr too would probably be helpful.

e.g. http://stackoverflow.com/q/29932255/1256624 was hard to diagnose without running the command manually.

**Comment by alexcrichton** [comment]
I think this is actually a symptom of https://github.com/rust-lang/rust/pull/24873, when working correctly gcc-rs is sure to forward all output from gcc up to the output of the build script itself. For now though I'm going to close as a dupe of that bug.
