### ISSUE TITLE
Cross compilation seems to be screwed up

### ISSUE THREAD

**Issue by SirVer** [alexcrichton/gcc-rs#45]
I am using this to cross compile to my small arm board. It works awesomly: https://github.com/japaric/ruststrap/blob/master/1-how-to-cross-compile.md

I ran into problems with https://github.com/rust-lang/time/, a dependency of mio. It compiled fine, but at the linking stage I got errors:

~~~
$ cargo build --target arm-unknown-linux-gnueabihf --release
Compiling gcc v0.3.8
Compiling byteorder v0.3.10
Compiling libc v0.1.8
Compiling bytes v0.2.9
Compiling bitflags v0.1.1
Compiling log v0.3.1
Compiling nix v0.3.7
Compiling time v0.1.26
Compiling mio v0.3.6
Compiling hello v0.1.0 (file:///usr/local/google/home/hrapp/prog/rust_arm_crosscompile)
... verbose errors skipped
 /usr/local/google/home/hrapp/prog/rust_arm_crosscompile/target/arm-unknown-linux-gnueabihf/release/deps/libtime-85f806c28787f8bd.rlib: error adding symbols: File format not recognized
~~~

I traced that to `time`'s c extension, build here: https://github.com/rust-lang/time/blob/master/build.rs
It seems to ignore the --target and happily build for another CPU. The fix is easy enough. In my own project I build with the `CC` variable set - but something seems fishy.

So this works:

~~~
$ CC=arm-linux-gnueabihf-gcc-4.8 cargo build --target arm-unknown-linux-gnueabihf --release
   Compiling gcc v0.3.8
   Compiling bytes v0.2.9
   Compiling byteorder v0.3.10
   Compiling bitflags v0.1.1
   Compiling libc v0.1.8
   Compiling log v0.3.1
   Compiling nix v0.3.7
   Compiling time v0.1.26
   Compiling mio v0.3.6
   Compiling hello v0.1.0 (file:///usr/local/google/home/hrapp/prog/rust_arm_crosscompile)
$ 
~~~

**Comment by alexcrichton** [comment]
Unfortunately this crate itself can't really deal much with cross compilation, it can only know that a cross compile is *happening*, but it needs to be instructed where the compiler and other tools are located. In this case you'll need to specify `CC` (as you've seen) or some derivative (e.g. `CC_arm-linux-gnueabihf=...`).

The default behavior of gcc-rs, however, is to just use `gcc` by default, which probably isn't going to change.

**Comment by SirVer** [comment]
Alex, I am a bit confused about the situation. Certainly I am missing something, this is how I am thinking:

I pass cargo the `--target` option and it seems to find the correct cross compiler by itself without me telling it anything else. I have to specify the linker in `.cargo/config` - which I already do not quite understand. I mean if it can guess the compiler, can't it guess the linker? But that is a tangent.

So, it seems that cargo knows the compiler and uses it apparently for all the dependencies too. Cargo is also the tool that compiles and runs `build.rs`, right? It seems to be picking the native compiler for that (which is correct of course) - since the build runs through just fine.

Now I wonder - if cargo understands about the differences of cross and native compiler and is the tool that runs `build.rs`, can't it pass the cross compiler to `build.rs` somehow, so that gcc-rs can pick it up and use it?

**Comment by alexcrichton** [comment]
Cargo actually has no knowledge about cross compilers, only that a cross compile is happening. All Rust compilers are cross compilers by default, but that's orthogonal to the linker/C compiler that's in use. Cargo itself has no knowledge about a C compiler or how it can be used and/or passed down to build scripts.

**Comment by SirVer** [comment]
Now I understand. Thanks for the explanation.
