### ISSUE TITLE
Add try_compile, returning Result<(), String>

### ISSUE THREAD

**Issue by seanmonstar** [alexcrichton/gcc-rs#48]
The `String` could be `stderr` from the command.

This could be used to try to provide help messages, by checking the stderr, noticing an error about something like a missing header file, and suggesting to the user instructions on how to install those headers.

**Comment by sfackler** [comment]
I'd like this as well.

**Comment by alexcrichton** [comment]
One thing I realized recently is that the [`get_compiler` method](http://alexcrichton.com/gcc-rs/gcc/struct.Config.html#method.get_compiler) may actually suffice for this pretty well, can you perhaps test out using that API and see if it works well? If you end up having to pass lots of your own flags and such I can see where that may not quite work out so well though :)

**Comment by dtolnay** [comment]
This is also tracked in #192.

**Comment by alexcrichton** [comment]
Fixed in https://github.com/alexcrichton/gcc-rs/pull/222
