### ISSUE TITLE
Can't compile C sources with `-lxcb` flag

### ISSUE THREAD

**Issue by Darksonn** [alexcrichton/gcc-rs#50]
I need to run the compiler with the flag `-lxcb` to compile my C sources, however all methods in this library for adding flags add them at the wrong location. I need the `-lxcb` flag after the sources.

I tried adding `.flag("-lxcb")` to the build file, however that added the flag before the sources, I also tried the `CFLAGS` environment variable, however that did the same.

What I get:

    running: "cc" "-O0" "-c" "-ffunction-sections" "-fdata-sections" "-m64" "-fPIC" "-I" "src" "-lxcb" "/home/user/src/nvim-wm/src/xcb/xcb.c" "-o" "/home/user/src/nvim-wm/target/debug/build/nvim-wm-c5c5e07d2e28bf98/out/src/xcb/xcb.o"

What I want:

    running: "cc" "-O0" "-c" "-ffunction-sections" "-fdata-sections" "-m64" "-fPIC" "-I" "src" "/home/user/src/nvim-wm/src/xcb/xcb.c" "-o" "/home/user/src/nvim-wm/target/debug/build/nvim-wm-c5c5e07d2e28bf98/out/src/xcb/xcb.o" "-lxcb"

**Comment by alexcrichton** [comment]
I don't think you need `-l` flags to compile object files, why does this compile require them?

**Comment by Darksonn** [comment]
The problem appeared to be that `#include <xcb/xcb.h>` thought it actually was `#include "xcb/xcb.h"` and as such used that file in my own repository.

When the step of compiling object files suddenly gives errors such as the following, I assumed I needed to tell it to use the library.

    /path/src/xcb/xcb.c:5:1: error: unknown type name ‘xcb_connection_t’
     xcb_connection_t *xcb_conn = 0;
     ^
