### ISSUE TITLE
Is hardcoding -mwin32 on windows targets a good idea?

### ISSUE THREAD

**Issue by bvinc83** [alexcrichton/gcc-rs#51]
See sfackler/rust-openssl#248

Adding the -mwin32 flag as default in gcc-rs is the reason that openssl-sys is failing to compile under Cygwin.  The openssl code seems to be expecting that, under Cygwin, the _WIN32 is not defined.

What do you feel is the best way to handle this problem?

It makes sense to me that since the -mwin32 flag is not a gcc default, that projects that need -mwin32 should add it to their gcc flags.

It doesn't make sense to me that projects that don't want -mwin32 should be required to opt out of it because gcc-rs has it as a default.

What do you think?

**Comment by alexcrichton** [comment]
To be honest I don't 100% know what this was doing, but it was added in https://github.com/alexcrichton/gcc-rs/pull/19 to apparently help with https://github.com/rust-lang/time/issues/45. 

@cybergeek94 perhaps you could comment a bit to this effect?

I think it'd be totally fine to add a flag to the builder which turns off passing this flag.

**Comment by cybergeek94** [comment]
If I'm perfectly honest, I have no idea what's going on here. It fixed the `time` crate building on Windows, that's the only consequence I had considered at the time.

**Comment by bvinc83** [comment]
-mwin32 just adds defines like _WIN32, which Microsoft always defines on Windows with their compiler.

It's hard to know exactly what the conventions are, but when it is defined, it usually means you're using msvc, or using the Windows API.

GCC, under cygwin, by default, does not have these defined, but has the option of adding ```-mwin32``` for anyone that needs it.  OpenSSL, when compiled under cygwin, is an example of code that is meant to be compiled under default settings.  If ```_WIN32``` is defined, it uses things like ```__int64```.

It just seems odd to me that something meant to compile under default gcc settings would need to add a flag to gcc-rs, which is why I opened the issue.

I wonder why it fixed the time crate.

**Comment by cybergeek94** [comment]
At the time, the `time` crate wasn't compiling because it expected those symbols to be linked in for the C shim. Now, it uses the `winapi-rs` crates which presumably are more robust with handling this. The PR can probably be reverted altogether, or otherwise undone.

**Comment by cybergeek94** [comment]
Removing the `-mwin32` flag seems to have fixed the problem. It didn't break `time` because that crate doesn't use `gcc-rs` anymore, and `rust-openssl/openssl-sys` now compiles successfully.

However, `rust-openssl` still doesn't compile on Windows:

```
C:\msys64\home\Austin\.cargo\registry\src\github.com-0a35038f75765ae4\connected_socket-0.0.6\src\lib.rs:6:5: 6:31 error: unresolved import `std::os::unix::io::AsRawFd`. Could not find `unix` in `std::os`
C:\msys64\home\Austin\.cargo\registry\src\github.com-0a35038f75765ae4\connected_socket-0.0.6\src\lib.rs:6 use std::os::unix::io::AsRawFd;
                                                                                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~
C:\msys64\home\Austin\.cargo\registry\src\github.com-0a35038f75765ae4\connected_socket-0.0.6\src\lib.rs:7:5: 7:29 error: unresolved import `std::os::unix::io::RawFd`. Could not find `unix` in `std::os`
C:\msys64\home\Austin\.cargo\registry\src\github.com-0a35038f75765ae4\connected_socket-0.0.6\src\lib.rs:7 use std::os::unix::io::RawFd;
                                                                                                              ^~~~~~~~~~~~~~~~~~~~~~~
```

I'm pretty sure this one isn't my fault. :smile:

@alexcrichton Should I open a PR then?

**Comment by alexcrichton** [comment]
Ok, thanks for the info @cybergeek94 and @bvinc83! I agree that this shouldn't be passed by default so I've removed it.

I'll do a minor version bump and if it ends up causing breakage I'll do a yank and a major version bump.
