### ISSUE TITLE
MinGW can't compile anything with -m64 flag on x86_64

### ISSUE THREAD

**Issue by mceier** [alexcrichton/gcc-rs#55]
On Windows with MinGW toolchain "-m64" flag causes "sorry, unimplemented: 64-bit mode not compiled in" error e.g. when compiling miniz-sys:

    C:\...\.cargo\registry\src\github.com-0a35038f75765ae4\miniz-sys-0.1.6\miniz.c:1:0: sorry, unimplemented: 64-bit mode not compiled in
    thread '<main>' panicked at 'explicit panic', C:\...\.cargo\registry\src\github.com-0a35038f75765ae4\gcc-0.3.13\src\lib.rs:510

miniz.c compiles fine without -m64 flag.

**Comment by alexcrichton** [comment]
This typically indicates that you're building for a 64-bit architecture while inside of a 32-bit MSYS shell, could you check to see if a 64-bit MSYS shell works?

**Comment by mceier** [comment]
I don't have msys installed, and build in rust 1.4 shell with mingw bin directory added to PATH.
I don't know what has recently changed, but about month ago I didn't have this problem (I don't compile the code on windows too often, so I can't pinpoint the date of change precisely).
With mingw-w64 there wasn't problem and I used it as a workaround.

**Comment by alexcrichton** [comment]
Could you paste the output of `rustc -V` and `cargo -V`? Also, are you sure the `gcc` in your path is a 64-bit compiler and not a 32-bit one?

**Comment by mceier** [comment]
I can't paste them right now (I will be able in about 14h) - but I downloaded and installed nightly version today (I try to update them every time before I try building rust projects on windows).
I'm not sure if gcc from mingw is 64-bit compiler - probably it isn't since the error.

**Comment by alexcrichton** [comment]
Yeah I'm guessing that a 32-bit gcc is being used by accident, and switching to a 64-bit gcc should fix things.

**Comment by mceier** [comment]
Assuming that gcc from mingw is 32-bit only, it should be compatible only with rust from 32-bit installer ?
How does gcc-rs decide to add -m64 flag - by the version of gcc found in the path or by the version of rust compiler or both ?
I did install rust using 64-bit installer and if gcc-rs adds -m64 based on rust version, maybe README.md should say that "gcc from mingw is compatible only with rust from 32-bit installer" ? 
I will try to check compatibility of gcc from mingw with rust from 32-bit installer in 14h.

**Comment by alexcrichton** [comment]
Yes if your installation of mingw-w64 only has a 32-bit compiler then it should work with the `i686-pc-windows-gnu` compiler (32-bit rustc)

**Comment by mceier** [comment]
It's not installation of mingw-w64 but mingw (http://www.mingw.org/) that has problem.
I just checked the compatibility of gcc from mingw with rust from 32-bit installer, and it compiled the code without problem, so I think that maybe message like "If you're using MinGW on Windows use 32-bit rust compiler" should be added to README.md ?

**Comment by alexcrichton** [comment]
Sure!

**Comment by alexcrichton** [comment]
Thanks for https://github.com/alexcrichton/gcc-rs/pull/56!
