### ISSUE TITLE
tests don't work on windows if run from D:\

### ISSUE THREAD

**Issue by oli-obk** [alexcrichton/gcc-rs#60]
The tests need to be run on the same drive as the temp folder.

```
thread 'gnu_define' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 17, message: "Das System kann die Datei nicht auf ein anderes Laufwerk verschieben.\r\n" } }', ../src/libcore\result.rs:732
```

The issue is that some files are moved instead of copied according to the error message and the docs: https://msdn.microsoft.com/en-us/library/windows/desktop/ms681382%28v=vs.85%29.aspx

**Comment by alexcrichton** [comment]
Oops, thanks for the report!
