### ISSUE TITLE
Support custom target files

### ISSUE THREAD

**Issue by phil-opp** [alexcrichton/gcc-rs#64]
Right now the crate uses only the target _string_ for automatic configuration. For example, it compiles the dependencies with `-fPIC` if the target string does not contain `i686` or `windows-gnu`. This can lead to surprising behavior when using custom target files since their values are completely ignored.

For example, the resulting library uses position independent code (and a global offset table) even if the target json contains `"relocation-model": "static"`… except for target files that have `i686` somewhere in their file name. And renaming the file is the only option to override this automatic behavior.

**Comment by alexcrichton** [comment]
Hm yeah this is surprising, although I don't think that this wants to necessarily start parsing JSON just yet (as that format is still relatively unstable). I'd be fine, however, adding some options to control the default emission of arguments like `-fPIC`
