### ISSUE TITLE
Illegal invocation of cl.exe when targeting i686-pc-windows-msvc from x86_64-apple-darwin

### ISSUE THREAD

**Issue by alexchandel** [alexcrichton/gcc-rs#66]
gcc-rs illegally invokes `cl.exe`'s `/Fo<pathname>` parameter by inserting a colon before the pathname, when cross-compiling from x86_64-apple-darwin to i686-pc-windows-msvc.

Invoking with `INCLUDE="$HOME/i686-pc-windows-msvc-w10/include;$HOME/i686-pc-windows-msvc-vc10/include" LIB="$HOME/i686-pc-windows-msvc-w10/lib;$HOME/i686-pc-windows-msvc-vc10/lib" TARGET_CC=cl.exe cargo build --target i686-pc-windows-msvc`, where `cl.exe` is a symlink to `clang-cl`, yields an error like:

```
   Compiling rust-crypto v0.2.34 (file:///Users/alex/GitHub/rust-crypto)
failed to run custom build command for `rust-crypto v0.2.34 (file:///Users/alex/GitHub/rust-crypto)`
Process didn't exit successfully: `/Users/alex/GitHub/rust-crypto/target/debug/build/rust-crypto-6ae07b54d3ad34fc/build-script-build` (exit code: 101)
--- stdout
TARGET = Some("i686-pc-windows-msvc")
OPT_LEVEL = Some("0")
PROFILE = Some("debug")
TARGET = Some("i686-pc-windows-msvc")
debug=true opt-level=0
HOST = Some("x86_64-apple-darwin")
TARGET = Some("i686-pc-windows-msvc")
TARGET = Some("i686-pc-windows-msvc")
HOST = Some("x86_64-apple-darwin")
CC_i686-pc-windows-msvc = None
CC_i686_pc_windows_msvc = None
TARGET_CC = Some("cl.exe")
TARGET = Some("i686-pc-windows-msvc")
HOST = Some("x86_64-apple-darwin")
CFLAGS_i686-pc-windows-msvc = None
CFLAGS_i686_pc_windows_msvc = None
TARGET_CFLAGS = None
CFLAGS = None
running: "cl.exe" "/nologo" "/MD" "/Z7" "/Fo:/Users/alex/GitHub/rust-crypto/target/i686-pc-windows-msvc/debug/build/rust-crypto-6ae07b54d3ad34fc/out/src/util_helpers.o" "/c" "src/util_helpers.c"
ExitStatus(ExitStatus(256))


command did not execute successfully, got: exit code: 1



--- stderr
error: unable to open output file ':/Users/alex/GitHub/rust-crypto/target/i686-pc-windows-msvc/debug/build/rust-crypto-6ae07b54d3ad34fc/out/src/util_helpers.o': 'No such file or directory'
1 error generated.
thread '<main>' panicked at 'explicit panic', /Users/alex/.cargo/registry/src/github.com-88ac128001ac3a9a/gcc-0.3.20/src/lib.rs:772
```

Notice the illegal argument `/Fo:/Users/alex/GitHub/rust-crypto/target/i686-pc-windows-msvc/debug/build/rust-crypto-6ae07b54d3ad34fc/out/src/util_helpers.o`. This should be `/Fo/Users/alex/GitHub/rust-crypto/target/i686-pc-windows-msvc/debug/build/rust-crypto-6ae07b54d3ad34fc/out/src/util_helpers.o`.

Indeed manually compiling with `INCLUDE="$HOME/i686-pc-windows-msvc-w10/include;$HOME/i686-pc-windows-msvc-vc10/include" LIB="$HOME/i686-pc-windows-msvc-w10/lib;$HOME/i686-pc-windows-msvc-vc10/lib" "cl.exe" "/nologo" "/MD" "/Z7" "/Fo/Users/alex/GitHub/rust-crypto/target/i686-pc-windows-msvc/debug/build/rust-crypto-6ae07b54d3ad34fc/out/src/util_helpers.o" "/c" "src/util_helpers.c"` works file.

**Comment by alexcrichton** [comment]
Huh, not sure where this leaked in... thanks for the report!

**Comment by alexchandel** [comment]
Wow immediate fix, thanks!
