### ISSUE TITLE
Rename the crate

### ISSUE THREAD

**Issue by tsion** [alexcrichton/gcc-rs#68]
Should this crate be renamed to something more generic like `c_compiler`? I've seen the current name cause confusion for people since they don't expect it to be able to work with MSVC, for example.

If a name change is desired this is potentially blocked on crates.io having support for renaming crates smoothly so dependent crate authors can be notified of the new name.

**Comment by alexcrichton** [comment]
Yeah in retrospect gcc was probably not the best name for this crate, but with a lack of renaming support on crates.io I'd prefer to not "break the world" now. Hopefully it can be understood that this crate strives to be cross platform which means using MSVC where needed!
