### ISSUE TITLE
support $CC, $CXX containing spaces

### ISSUE THREAD

**Issue by sourcefrog** [alexcrichton/gcc-rs#75]
(from https://github.com/rust-lang/rust/issues/32914)

A setting of `CC='ccache gcc'` is accepted by most Linux build tools but causes trouble for Rust. When it builds an argv to execute the compiler it treats that whole string as the binary name.

This is apparently [intentional](https://github.com/alexcrichton/gcc-rs#external-configuration-via-environment-variables) but might not be optimal.

Probably better is to either 

 - split on spaces 
 - or perhaps use some shell-like parser to break into words, which might allow for quoted spaces etc

```
cargo:rustc-link-lib=static=brotli-dec
cargo:rustc-link-search=native=/home/mbp/src/conserve/target/debug/build/brotli-sys-c29cf30a86d86a13/out
TARGET = Some("x86_64-unknown-linux-gnu")
OPT_LEVEL = Some("0")
PROFILE = Some("debug")
TARGET = Some("x86_64-unknown-linux-gnu")
debug=true opt-level=0
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CXX_x86_64-unknown-linux-gnu = None
CXX_x86_64_unknown_linux_gnu = None
HOST_CXX = None
CXX = Some("ccache c++")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CXXFLAGS_x86_64-unknown-linux-gnu = None
CXXFLAGS_x86_64_unknown_linux_gnu = None
HOST_CXXFLAGS = None
CXXFLAGS = None
running: "ccache c++" "-O0" "-ffunction-sections" "-fdata-sections" "-g" "-m64" "-fPIC" "-I" "brotli/enc" "-I" "src" "-o" "/home/
mbp/src/conserve/target/debug/build/brotli-sys-c29cf30a86d86a13/out/src/brotli_capi.o" "-c" "src/brotli_capi.cc"

failed to execute command: No such file or directory (os error 2)
Is `ccache c++` not installed?
```

**Comment by sourcefrog** [comment]
https://github.com/comex/rust-shlex/blob/master/src/lib.rs might help for handling this.

**Comment by alexcrichton** [comment]
Yeah right now we don't want to split on spaces because that precludes any compiler with spaces in the path name (e.g. can be common on Windows).

I'd be fine though just having a special whitelist where if `CC` start with "ccache " then we peel that off and use that instead.

**Comment by alexcrichton** [comment]
Ok, I've commit specific logic for this for now as it seems common, could you try it out and see if it works for you?

**Comment by sourcefrog** [comment]
Would you like a PR to use rust-shlex for a more general solution, or would you rather just stay on this?  (And, is that dependency ok?)

**Comment by alexcrichton** [comment]
Yeah I'd prefer to not invent a shell escaping syntax just yet and stick with just a small prefix for now

**Comment by sourcefrog** [comment]
c934cb3 fixes it for me, thanks.

**Comment by alexcrichton** [comment]
Thanks for checking!
