### ISSUE TITLE
(optionally) emit warning messages from C(++) compiler

### ISSUE THREAD

**Issue by mystor** [alexcrichton/gcc-rs#81]
Once rust-lang/cargo#2630 lands, it would be awesome if there was an option to tell gcc-rs to forward the warning messages produced by the c/c++ compiler, but prefixed with `cargo:warning=`, to the build script's standard out. This would be useful for getting and fixing error messages in C++ and C code which is compiled through the build plugin as a companion to rust code.

**Comment by alexcrichton** [comment]
Indeed! I hope to do this by default once that lands

**Comment by mystor** [comment]
In rust 1.11, I believe cargo:warning is now stable. Should we just collect the standard error from the compiler processes, and print anything written to it with each line prefixed with `cargo:warning=`?
