### ISSUE TITLE
Fix MSVC compiler detection when using the Visual C++ 2015 build tools standalone package.

### ISSUE THREAD

**Issue by TechnoMancer** [alexcrichton/gcc-rs#83]
gcc-rs does not properly detect the msvc compiler when installed with the Visual C++ 2015 build tools package from http://landinghub.visualstudio.com/visual-cpp-build-tools

The resulting registry keys are here: [VSKeys.txt](https://github.com/alexcrichton/gcc-rs/files/346239/VSKeys.txt)

rustc correctly determines the install location to find link.exe

**Comment by retep998** [comment]
More specifically `gcc-rs` is looking for `InstallDir` in `HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\VisualStudio\14.0` while rustc looks for `14.0` in `HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\VisualStudio\SxS\VC7`. The former only exists when you have a VS installation while the latter exists when you have a VC++ installation. 

`gcc-rs` should not care about VS and only care about VC++, so updating the logic in `gcc-rs` to more closely reflect [rustc's logic](https://github.com/rust-lang/rust/blob/master/src/librustc_trans/back/msvc/mod.rs) would definitely help. Perhaps even splitting the logic from rustc into a separate crate and adding in header/cl support and then making `gcc-rs` depend on that, and eventually rustc can too (when rustbuild finally becomes dominant and rustc can depend on external crates).

**Comment by alexcrichton** [comment]
Yeah the logic gcc-rs was intended to match that of the compiler, and while it did long ago they have now significantly diverged!

Sounds like we just need to update the logic to match again. Would be good to ensure there's an appveyor build for this to prevent regressions as well.

**Comment by retep998** [comment]
While appveyor would be useful, it would only help with its specific configuration, and not all the various configurations that are out there, such as the standalone VC++ build tools.

**Comment by alexcrichton** [comment]
Ok, I've updated in https://github.com/alexcrichton/gcc-rs/pull/85, @TechnoMancer can you try that out and see if it works for you? I don't personally have this installed just yet so I may have missed something!

**Comment by TechnoMancer** [comment]
I noticed this because building miniz-sys fails to build with my setup, I guess everything will have to update before that would change, when I have some time I might try forcing the gcc-rs version it uses to the git repo and see if it fixes it.

**Comment by alexcrichton** [comment]
@TechnoMancer you should be able to test it out by adding this to your `Cargo.toml` (and I think using beta or nightly Cargo right now):

```toml
[replace]
"gcc:0.3.28" = { git = "https://github.com/alexcrichton/gcc-rs" }
```

**Comment by TechnoMancer** [comment]
With that it does appear to work now.

**Comment by alexcrichton** [comment]
Awesome, thanks @TechnoMancer!
