### ISSUE TITLE
gcc-rs picks up .o files from previous builds unless cargo clean is run

### ISSUE THREAD

**Issue by jbaublitz** [alexcrichton/gcc-rs#88]
I'm unsure whether this will be considered a cargo or gcc-rs bug but I ran into an interesting bit of behavior using cargo and gcc-rs together. Using gcc-rs in ```build.rs```, I specified a ```.c``` file to build. I then changed the name of the ```.c``` file and built again. Linking started to fail with the following error message:

```
/home/jbaublitz/Source/Repos/Projects/surge/target/debug/build/surge-29091b15abafbbfc/out/libnetlink.a(netlink.o):(.rodata.nl_route+0x0): first defined here
/home/jbaublitz/Source/Repos/Projects/surge/target/debug/build/surge-29091b15abafbbfc/out/libnetlink.a(netlink_macros.o):(.rodata.nl_unused+0x0): multiple definition of `nl_unused'
```

and this message came up for all of the variables defined globally in my ```.c``` file. It seems that either cargo or gcc-rs is picking up both of the ```.o``` files and creating a ```.a``` file out of the stale and current ```.o``` files so therefore it believes the variables are defined twice.

This is the link to the build.rs file in question.

https://github.com/jbaublitz/surge/blob/master/build.rs

Does this seem like a gcc-rs issue or should I file it with cargo?

**Comment by alexcrichton** [comment]
I think this is indeed the right place for this bug! I believe what's happening here is that gcc-rs isn't removing the archive before it adds object files into it, so if the archive already exists it'll just add more objects into it (the behavior of `ar`).

The specific code is [here](https://github.com/alexcrichton/gcc-rs/blob/master/src/lib.rs#L546-L553) and it probably just needs a `let _ = fs::remove_file(&dst);` above that. Could you try that out and see if it works for you?

**Comment by jbaublitz** [comment]
Thanks for the quick response! I will try to test it sometime this week and will report back.

**Comment by jbaublitz** [comment]
I have finally had some time to look into this. Just to clarify, do you mean I should add that code into the gcc-rs crate on my machine and compile and see if that fixes it? If so, I will try that out in the next few days.

**Comment by alexcrichton** [comment]
Ah yeah just right before we execute `ar` insert that call to `fs::remove_file`
