### ISSUE TITLE
Support for overriding CC, CXX, CFLAGS, CXXFLAGS from a config file

### ISSUE THREAD

**Issue by crlf0710** [alexcrichton/gcc-rs#97]
I'm a windows user, and i've got mingw64 installed. Either add mingw64 dirs into PATH or setting CC CXX etc i can get things compiled. However i prefer not to do so, because i've got msys2 toolchains and msvc toolchains too. I'd rather keep things separated instead of messing them together.

I wonder if gcc-rs can load these from a separate overriding config file (only used by itself), so i don't have to tweak the whole system environment.

**Comment by alexcrichton** [comment]
Thanks for the report! I think that this functionality is covered by https://github.com/alexcrichton/gcc-rs/issues/82, so I'm going to close in favor of that. 

I'm still in favor of doing though!
