### ISSUE TITLE
Support for opt-level {s,z}

### ISSUE THREAD

**Issue by joerg-krause** [alexcrichton/gcc-rs#98]
Cargo now supports `opt-level="s"`. However, cross-compiling using this crate fails with, e.g.:

```
error: failed to run custom build command for `liblmdb-sys v0.2.1`
process didn't exit successfully: `/home/joerg/Development/git/librespot/target/release/build/liblmdb-sys-4670f3f0ac13a883/build-script-build` (exit code: 101)
--- stdout
TARGET = Some("armv5te-unknown-linux-musl")
OPT_LEVEL = Some("s")
```

**Comment by alexcrichton** [comment]
Thanks for the report! I think I've fixed this in https://github.com/alexcrichton/gcc-rs/commit/392fab5e7b3484c3a10240611c52a6d4ca61241f, but could you try it out just to make sure?

**Comment by joerg-krause** [comment]
I just noticed the `[replace]` feature of Cargo. So I gave it a try and it works :smile: Many thanks!

**Comment by alexcrichton** [comment]
Glad it works!
